services:
  - type: web
    name: telegram-gift-bot
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y wget unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y ./google-chrome-stable_current_amd64.deb
      wget https://storage.googleapis.com/chrome-for-testing-public/120.0.6099.109/linux64/chromedriver-linux64.zip
      unzip chromedriver-linux64.zip
      mv chromedriver-linux64/chromedriver /usr/local/bin/
      pip install -r requirements.txt
    startCommand: gunicorn app:app
